name: Minify Map JSON
on:
  push:
    branches:
      - master
    paths:
      - 'boundaries.geo.json'
  workflow_dispatch:
jobs:
  processJson:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update TopoJSON boundaries
        run: |
          sudo npm install -g mapshaper
          mapshaper ./boundaries.geo.json snap -clean -o force precision=0.0001 format=geojson ./boundaries.geo.json
          sudo npm install -g topojson-server
          geo2topo ./boundaries.geo.json -q 50000 > ./website/data/boundaries.topo.json
          python3 ./.github/scripts/merge_csv_to_topojson.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update TopoJSON boundaries
          title: Update TopoJSON boundaries
          body: Clean and minify GeoJSON and process to TopoJSON
          branch: geo-to-topo