name: topo auto updater (PR)

on:
  pull_request:
    paths:
    - 'website/data/library_services_information.csv'

jobs:
  auto-topo-updater:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - uses: christianvuerings/add-labels@v1
      with:
        labels: |
          auto update
          data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge CSV to TopoJSON
      run: |
        python3 ./.github/scripts/merge_csv_to_topojson.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: merge csv data to topo